"use client";

import { BriefingResponse, Cluster } from "./types";

export function clusterBriefingToMarkdown(
  cluster: Cluster,
  briefing: BriefingResponse | null,
): string {
  const now = new Date().toISOString();
  const lines: string[] = [];
  lines.push(`# Pulse Briefing: ${cluster.dominantTitle}`);
  lines.push("");
  lines.push(`Generated ${now}`);
  lines.push("");
  lines.push(`**Category:** ${cluster.category}`);
  lines.push(
    `**Coordinates:** ${cluster.lat.toFixed(2)}, ${cluster.lng.toFixed(2)}`,
  );
  lines.push(`**Events in cluster:** ${cluster.events.length}`);
  if (briefing) {
    lines.push(`**Severity:** ${briefing.severity}/10`);
  }
  lines.push("");

  if (briefing) {
    if (briefing.summary) {
      lines.push("## What happened");
      lines.push(briefing.summary);
      lines.push("");
    }
    if (briefing.significance) {
      lines.push("## Why it matters");
      lines.push(briefing.significance);
      lines.push("");
    }
    if (briefing.connected_events && briefing.connected_events.length > 0) {
      lines.push("## Connected events");
      for (const e of briefing.connected_events) lines.push(`- ${e}`);
      lines.push("");
    }
    if (briefing.historical_parallels) {
      lines.push("## Historical parallels");
      lines.push(briefing.historical_parallels);
      lines.push("");
    }
    if (briefing.key_actors && briefing.key_actors.length > 0) {
      lines.push("## Key actors");
      for (const a of briefing.key_actors) lines.push(`- ${a}`);
      lines.push("");
    }
  }

  lines.push("## Sources");
  for (const e of cluster.events) {
    if (e.url) {
      lines.push(`- [${e.source}] ${e.title}`);
      lines.push(`  ${e.url}`);
    } else {
      lines.push(`- [${e.source}] ${e.title}`);
    }
  }
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push("Generated by Pulse, Global News Intelligence Globe.");

  return lines.join("\n");
}

export function regionToMarkdown(
  regionName: string,
  clusters: Cluster[],
): string {
  const now = new Date().toISOString();
  const lines: string[] = [];
  lines.push(`# Pulse Regional Briefing: ${regionName}`);
  lines.push("");
  lines.push(`Generated ${now}`);
  lines.push("");
  lines.push(`**Clusters tracked:** ${clusters.length}`);
  const totalEvents = clusters.reduce((s, c) => s + c.events.length, 0);
  lines.push(`**Total events:** ${totalEvents}`);
  lines.push("");

  const byCat = new Map<string, Cluster[]>();
  for (const c of clusters) {
    const arr = byCat.get(c.category) ?? [];
    arr.push(c);
    byCat.set(c.category, arr);
  }
  lines.push("## Category breakdown");
  for (const [cat, items] of Array.from(byCat.entries()).sort(
    (a, b) => b[1].length - a[1].length,
  )) {
    lines.push(`- **${cat}**: ${items.length} clusters`);
  }
  lines.push("");

  lines.push("## Clusters");
  for (const c of clusters) {
    lines.push(`### ${c.dominantTitle}`);
    lines.push(`*${c.category} • ${c.events.length} events*`);
    for (const e of c.events.slice(0, 5)) {
      lines.push(`- [${e.source}] ${e.title}${e.url ? ` (${e.url})` : ""}`);
    }
    lines.push("");
  }
  lines.push("---");
  lines.push("");
  lines.push("Generated by Pulse, Global News Intelligence Globe.");
  return lines.join("\n");
}

export function downloadMarkdown(filename: string, content: string) {
  const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  link.click();
  URL.revokeObjectURL(url);
}
